name: flutter_girlies_store
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #cloud_firestore: 0.8.2+3
  #firebase_auth: ^0.5.14
  #firebase_auth: 0.7.0


  #firebase_database: ^1.0.2
  #firebase_storage: ^1.0.0
  firebase_storage:
  shared_preferences: "^0.4.2"

  #firebase_database: 1.0.3

  firebase_auth: ^0.11.1+12
  firebase_database: ^3.0.5
  cloud_firestore: ^0.12.7+1

  url_launcher: ^5.0.2
  flutter_launcher_icons: ^0.7.2+1
  share: ^0.6.2
  flutter_launch: ^0.2.0

 # flutter_email_sender: ^2.0.2
  #square_in_app_payments: ^1.1.0


  image_picker: 0.4.12+1
  #image_picker: ^0.4.10

  image :  ^2.0.7
  path_provider: ^0.5.0+1
  isolate: ^2.0.2
  photo_view: ^0.4.2
  #photo_view: ^0.2.2
  intl: ^0.15.8

  carousel_pro: ^1.0.0

  #image_cropper: ^0.0.4

  #flutter_image_compress: ^0.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
#


flutter_icons:
  image_path: "icon/aldrey.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
   # - images/mozaik.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages


  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: fonts/MyFlutterApp.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
